[WIP] generate export hash for helper process and process template
ProcessMaker/wizard-templates pull request #56
Opened 2024-05-10 17:44 UTC by sanjacornelius

TEST

2024-05-13 18:56 UTC, estebangallego approved these changes

2024-05-15 02:21 UTC, ryancooley requested changes

2024-05-15 02:21 UTC, ryancooley commented on .github/workflows/scripts/generate_index.php
> +        usort($templates, function($a, $b) { return strcmp($a['template_details']['card-title'], $b['template_details']['card-title']); });
@sanjacornelius There are some pretty deeply nested array paths here. Should we add some checks to make sure the expected keys actually exist?

2024-05-15 02:21 UTC, ryancooley commented on .github/workflows/scripts/generate_index.php
> +            $categories[$currentCategory][$templateName]['template_details']['helper_process_hash'] = compute_hash(json_encode($data['export'][$data['root']]['attributes']));
Same here.

2024-05-15 02:21 UTC, ryancooley commented on .github/workflows/scripts/generate_index.php
> +            $categories[$currentCategory][$templateName]['template_details']['template_process_hash'] = compute_hash(json_encode($data['export'][$data['root']]['attributes']));
And here.

2024-05-15 21:01 UTC, sanjacornelius commented
Hey @ryancooley code has been updated. Can you please review?

2024-05-15 21:02 UTC, sanjacornelius commented on .github/workflows/scripts/generate_index.php
> +        usort($templates, function($a, $b) { return strcmp($a['template_details']['card-title'], $b['template_details']['card-title']); });
Hey @ryancooley sure I'll add some checks!

2024-05-15 21:02 UTC, sanjacornelius commented on .github/workflows/scripts/generate_index.php
> +            $categories[$currentCategory][$templateName]['template_details']['helper_process_hash'] = compute_hash(json_encode($data['export'][$data['root']]['attributes']));
👍

2024-05-15 21:02 UTC, sanjacornelius commented on .github/workflows/scripts/generate_index.php
> +            $categories[$currentCategory][$templateName]['template_details']['template_process_hash'] = compute_hash(json_encode($data['export'][$data['root']]['attributes']));
For the `$categories` array, there's a function called `initializeTemplateStructure()` which is used to assign values. 

Here's an example of how it's used: 
`$categories[$currentCategory][$templateName] = initializeTemplateStructure();`

This function initializes all the necessary keys in the `$categories` array. This ensures that the structure of the `$categories` is properly set up. 

Here's what the `initializeTemplateStructure()` function looks like:

```
function initializeTemplateStructure()
{
    return [
        "helper_process" => "",
        "template_process" => "",
        "config_collection" => "",
        "template_details" => [
            "card-title" => "",
            "card-excerpt" => "",
            "modal-excerpt" => "",
            "modal-description" => "",
            'version' => "",
            'unique-template-id' => "",
            "helper_process_hash" => "",
            "template_process_hash" => "",
        ],
        "assets" => [
            "icon" => "",
            "card-background" => "",
            "slides" => [],
            "launchpad"  => [
                "process-card-background" => "",
                "slides" => [],
            ]
        ],
        "connected_accounts" => []
    ];
}
```

2024-06-10 02:01 UTC, closed without merging